[[constraint]]
  name = "github.com/aws/aws-lambda-go"
  version = "^1.4"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "^1.2"

[prune]
  go-tests = true
  unused-packages = true
